# Centralize constant values used across the project

lotr_keywords = [
    "lord of the rings",
    "lotr",
    "tolkien",
    "middle-earth",
    "middle earth",
    "frodo",
    "samwise",
    "sam",
    "gollum",
    "smeagol",
    "aragorn",
    "strider",
    "legolas",
    "gimli",
    "boromir",
    "faramir",
    "gandalf",
    "saruman",
    "radagast",
    "sauron",
    "the dark lord",
    "mordor",
    "the shire",
    "rivendell",
    "gondor",
    "rohan",
    "isengard",
    "orthanc",
    "barad-dûr",
    "the one ring",
    "my precious",
    "hobbit",
    "hobbitses",
    "shirefolk",
    "elves",
    "men",
    "dwarves",
    "orcs",
    "uruk-hai",
    "nazgul",
    "wraith",
    "ringwraith",
    "witch-king",
    "balrog",
    "numenor",
    "eowyn",
    "arwen",
    "galadriel",
    "elrond",
    "thranduil",
    "theoden",
    "eomer",
    "shadowfax",
    "mount doom",
    "eye of sauron",
    "palantir",
    "mithril",
    "anduril",
    "sting",
    "glamdring",
    "orcish",
    "black speech",
    "white council",
    "the fellowship",
    "fellowship of the ring",
    "two towers",
    "return of the king",
    "silmarillion",
    "beren and luthien",
    "children of hurin",
    "rings of power",
    "numenorean",
    "valinor",
    "undying lands",
    "took",
    "brandybuck",
    "baggins",
    "bilbo",
    "thorin",
    "bard the bowman",
    "smaug",
    "battle of the five armies",
    "erebor",
    "lonely mountain",
    "mirkwood",
    "elendil",
    "isildur",
    "gondorian",
    "rohirrim",
    "white tree of gondor",
    "seven rings",
    "dunedain",
    "halfling",
    "grey havens",
    "the great eye",
    "black gate",
    "argonath",
    "red book of westmarch",
    "khamul",
    "fell beast",
    "grima",
    "wormtongue",
    "denethor",
    "tom bombadil",
    "goldberry",
    "barrow wights",
    "scouring of the shire",
    "oliphaunt",
    "mumakil",
    "durin",
    "khazad-dum",
    "balin",
    "dwalin",
    "oathbreakers",
    "dead men of dunharrow",
    "great eagles",
    "gwaihir",
    "eagle of the north",
    "ring bearer",
    "nine walkers",
    "shelob",
    "ungoliant",
    "ent",
    "treebeard",
    "quickbeam",
    "fangorn",
    "orthanc",
    "sword that was broken",
]

LOTR_WARNING = "Our system has detected possible anti-Lord of the Rings sentiment in your post. Continuing to engage in this behavior may result in disciplinary action. 🔨"