# Centralize constant values used across the project

LOTR_KEYWORDS = [
    "lord of the rings",
    "lotr",
    "tolkien",
    "middle-earth",
    "middle earth",
    "frodo",
    "gollum",
    "smeagol",
    "aragorn",
    "strider",
    "legolas",
    "gimli",
    "boromir",
    "faramir",
    "gandalf",
    "saruman",
    "radagast",
    "sauron",
    "the dark lord",
    "mordor",
    "the shire",
    "rivendell",
    "gondor",
    "rohan",
    "isengard",
    "orthanc",
    "barad-dûr",
    "the one ring",
    "hobbit",
    "hobbitses",
    "shirefolk",
    "uruk-hai",
    "nazgul",
    "wraith",
    "ringwraith",
    "witch-king",
    "balrog",
    "numenor",
    "eowyn",
    "arwen",
    "galadriel",
    "elrond",
    "thranduil",
    "theoden",
    "eomer",
    "shadowfax",
    "mount doom",
    "eye of sauron",
    "palantir",
    "mithril",
    "anduril",
    "glamdring",
    "orcish",
    "the fellowship",
    "fellowship of the ring",
    "two towers",
    "return of the king",
    "silmarillion",
    "beren and luthien",
    "children of hurin",
    "rings of power",
    "numenorean",
    "valinor",
    "undying lands",
    "brandybuck",
    "baggins",
    "bilbo",
    "thorin",
    "bard the bowman",
    "smaug",
    "battle of the five armies",
    "erebor",
    "lonely mountain",
    "mirkwood",
    "elendil",
    "isildur",
    "gondorian",
    "rohirrim",
    "white tree of gondor",
    "seven rings",
    "dunedain",
    "halfling",
    "grey havens",
    "the great eye",
    "black gate",
    "argonath",
    "red book of westmarch",
    "khamul",
    "grima",
    "wormtongue",
    "denethor",
    "tom bombadil",
    "goldberry",
    "barrow wights",
    "scouring of the shire",
    "oliphaunt",
    "mumakil",
    "durin",
    "khazad-dum",
    "balin",
    "dwalin",
    "oathbreakers",
    "dead men of dunharrow",
    "great eagles",
    "gwaihir",
    "eagle of the north",
    "ring bearer",
    "nine walkers",
    "shelob",
    "ungoliant",
    "treebeard",
    "quickbeam",
    "fangorn",
    "orthanc",
    "sword that was broken",
]

LOTR_WARNING = "Our system has detected possible anti-Lord of the Rings sentiment in your post. Continuing to engage in this behavior may result in disciplinary action. 🔨"

PODCAST_NOTIFICATION_CHANNEL_NAME = "podcast-chatter"

INTROS_CHANNEL_NAME = "intros-bios"

GENERAL_PURPOSE_CHANNEL_NAME = "general"

NEW_PODCAST_ALERT = "🚨🎙️ NEW EPISODE! 🎙️🚨"

BOT_READY_MSG = """
**Hello Dinky Squad! I'm back and better than ever! 🤖. Type /help to learn more**
## Changes
- Fix - Fixed a bug that posted the latest episode on every bot startup
"""
