version: '3.8'

services:
  dinkybot_main:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.main

  dinkybot_dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
