services:
  dinkybot_main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dinkybot_main  
    env_file:
      - .env.main
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped

  dinkybot_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dinkybot_dev   
    env_file:
      - .env.dev
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped                 