name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: bluedragon
    steps:
      - uses: actions/checkout@v2
      
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: Build and deploy with Docker Compose
        run: cd docker && docker-compose up -d --build