on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 UTC (5:00 AM Central Daylight, 4:00 AM Central Standard)

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file for main
        run: |
          printf '%s' "${{ secrets.ENV_FILE_MAIN }}" > .env.main

      - name: Create .env file for dev
        run: |
          printf '%s' "${{ secrets.ENV_FILE_DEV }}" > .env.dev

      - name: Build containers with latest base images
        run: docker compose build --pull

      - name: Deploy containers
        run: docker compose up -d --force-recreate

      - name: Clean up unused Docker resources
        run: docker system prune -af --volumes
