on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file for main
        run: echo "${{ secrets.ENV_FILE_MAIN }}" > .env.main

      - name: Create .env file for dev
        run: echo "${{ secrets.ENV_FILE_DEV }}" > .env.dev

      - name: Build and deploy containers
        run: docker compose up -d --build
